CREATE TABLE telco_customers (
    customer_id TEXT,
    gender TEXT,
    age INTEGER,
    under_30 TEXT,
    senior_citizen TEXT,
    married TEXT,
    dependents TEXT,
    number_of_dependents INTEGER,
    country TEXT,
    state TEXT,
    city TEXT,
    zip_code INTEGER,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    population INTEGER,
    quarter TEXT,
    referred_a_friend TEXT,
    number_of_referrals INTEGER,
    tenure_in_months INTEGER,
    offer TEXT,
    phone_service TEXT,
    avg_monthly_long_distance_charges DOUBLE PRECISION,
    multiple_lines TEXT,
    internet_service TEXT,
    internet_type TEXT,
    avg_monthly_gb_download INTEGER,
    online_security TEXT,
    online_backup TEXT,
    device_protection_plan TEXT,
    premium_tech_support TEXT,
    streaming_tv TEXT,
    streaming_movies TEXT,
    streaming_music TEXT,
    unlimited_data TEXT,
    contract TEXT,
    paperless_billing TEXT,
    payment_method TEXT,
    monthly_charge DOUBLE PRECISION,
    total_charges DOUBLE PRECISION,
    total_refunds DOUBLE PRECISION,
    total_extra_data_charges INTEGER,
    total_long_distance_charges DOUBLE PRECISION,
    total_revenue DOUBLE PRECISION,
    satisfaction_score INTEGER,
    customer_status TEXT,
    churn_label TEXT,
    churn_score INTEGER,
    cltv INTEGER,
    churn_category TEXT,
    churn_reason TEXT
);

